---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
